- alias: 'Wake Me Up'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_time.state }}'
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.alarmweekday
            state: 'on'
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
      - condition: state
        entity_id: input_boolean.alarmweekday
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.master_bedroom
      data:
        profile: relax
        transition: 300
    - service: notify.pushbullet
      data:
        message: 'Good morning. Time to Wake Up!'
        title: ''
